  version: "3"
  services:
    postgres:
      image: postgres:latest
      container_name: postgres
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=postgres
        - POSTGRES_DB=bookstore
      restart: always
    # APP*****************************************
    bookstore:
      image: bookstore:latest
      container_name: bookstore
      ports:
        - 8080:8080
      restart: always
      depends_on:
        - postgres
      links:
        - postgres
    # Consul+Registrator*****************************************
    consul:
      image: gliderlabs/consul-server:latest
      container_name: consul
      ports:
        - "8400:8400"
        - "8500:8500"
        - "53:53/udp"
        - "8301-8302/udp"
        - "8300-8300/tcp"
      command: "-server -bootstrap"

    registrator:
      image: gliderlabs/registrator
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock
      command: "-cleanup -resync 30 consul://consul:8500"
      depends_on:
        - consul